name: deploy ordersystem with k8s
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET}}
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name 2team-cluster --region ap-northeast-2

      - name: login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker images to ecr
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: noexit
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
           -f ./Dockerfile .
           docker push $REGISTRY/$REPOSITORY:latest

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./k8s/noexit_depl.yml
          kubectl rollout restart deployment noexit-deployment -n e1i3
